server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: http://core-service:8081
          predicates:
            - Path=/api/**
  main:
    web-application-type: reactive


logging:
  level:
    org.springframework.cloud.gateway: DEBUG