server:
  port: 8080  # ????, ?? ??????? ????? ???????? Gateway

spring:
  application:
    name: api-gateway  # ??? ???????
  cloud:
    gateway:
      routes:
        - id: core-service  # ?????????? ????????????? ????????
          uri: lb://core-service  # lb:// ???????? ???????????? ????????
          predicates:
            - Path=/api/**
  main:
    web-application-type: reactive


logging:
  level:
    org.springframework.cloud.gateway: DEBUG